- name: Start GCP vm
  hosts: localhost
  connection: local

  collections:
    - google.cloud

  vars:
    service_account_file: "{{ lookup('env', 'GOOGLE_APPLICATION_CREDENTIALS') }}"
    has_service_account_file: "{{ service_account_file | length > 0 and service_account_file is file }}"
    auth_kind: ""

  tasks:
    - name: Start the GCP vm using service account file
      when: has_service_account_file
      block:
        - name: Start the GCP vm using service account file
          google.cloud.gcp_compute_instance:
            auth_kind: serviceaccount
            service_account_file: "{{ service_account_file }}"
            project: "{{ project }}"
            zone: "{{ zone }}"
            name: "{{ name }}"
            status: RUNNING
          register: result
          ignore_errors: yes
        
        - name: gather information about the vm instance
          google.cloud.gcp_compute_instance_info:
            auth_kind: serviceaccount
            service_account_file: "{{ service_account_file}}"
            project: "{{ project }}"
            zone: "{{ zone }}"
            filters:
              - "name={{ name }}"
          register: vm_info
          
        - copy:
            content: "{{ vm_info }}"
            dest: qtorque_outputs.json
     
    - name: Start the GCP vm using Workload Identity Federation
      when: not has_service_account_file or result.failed
      block:
        - name: Start the GCP vm using Workload Identity Federation
          google.cloud.gcp_compute_instance:
            auth_kind: application
            project: "{{ project }}"
            zone: "{{ zone }}"
            name: "{{ name }}"
            status: RUNNING
          register: result
          ignore_errors: yes
        
        - name: gather information about the vm instance
          google.cloud.gcp_compute_instance_info:
            auth_kind: application
            project: "{{ project }}"
            zone: "{{ zone }}"
            filters:
              - "name={{ name }}"
          register: vm_info
          
        - copy:
            content: "{{ vm_info }}"
            dest: qtorque_outputs.json
    
    - name: Start the GCP vm using machine account (last fallback)
      when: result is defined and (result.failed | default(true))
      block:
        - name: Start the GCP vm using machine account (last fallback)
          google.cloud.gcp_compute_instance:
            auth_kind: machineaccount
            project: "{{ project }}"
            zone: "{{ zone }}"
            name: "{{ name }}"
            status: RUNNING  
          register: result
        
        - name: gather information about the vm instance
          google.cloud.gcp_compute_instance_info:
            auth_kind: machineaccount
            project: "{{ project }}"
            zone: "{{ zone }}"
            filters:
              - "name={{ name }}"
          register: vm_info
          
        - copy:
            content: "{{ vm_info }}"
            dest: qtorque_outputs.json
